api_platform:
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
  collection:
    pagination:
      enabled: false
      enabled_parameter_name: 'pagination'
      items_per_page_parameter_name: 'count'
      page_parameter_name: 'page'
      partial_parameter_name: 'partial'
