nelmio_cors:
    defaults:
        allow_origin: ['%env(API_URL)%']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
        # allow_credentials: false
    paths:
        '^/api/':
            allow_origin: ['%env(API_URL)%']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600
        # '^/api/secured/':
        #     allow_origin: ['https://example.com']
        #     allow_headers: ['Content-Type', 'Authorization']
        #     allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
        #     max_age: 3600
